/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fproject;

import javax.swing.JOptionPane;

/**
 *
 * @author malak
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newaccbutton = new javax.swing.JButton();
        modifybutton = new javax.swing.JButton();
        closebutton = new javax.swing.JButton();
        depositbutton = new javax.swing.JButton();
        withdrawbutton = new javax.swing.JButton();
        transferbutton = new javax.swing.JButton();
        interestbutton = new javax.swing.JButton();
        viewbutton = new javax.swing.JButton();
        searchbutton = new javax.swing.JButton();
        transbutton = new javax.swing.JButton();
        logoutbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        newaccbutton.setBackground(new java.awt.Color(204, 204, 255));
        newaccbutton.setText("Add New Account");
        newaccbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newaccbuttonActionPerformed(evt);
            }
        });

        modifybutton.setBackground(new java.awt.Color(204, 204, 255));
        modifybutton.setText("Modify Account");
        modifybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifybuttonActionPerformed(evt);
            }
        });

        closebutton.setBackground(new java.awt.Color(204, 204, 255));
        closebutton.setText("Close Account");
        closebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebuttonActionPerformed(evt);
            }
        });

        depositbutton.setBackground(new java.awt.Color(204, 255, 255));
        depositbutton.setText("Deposit");
        depositbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositbuttonActionPerformed(evt);
            }
        });

        withdrawbutton.setBackground(new java.awt.Color(204, 255, 255));
        withdrawbutton.setText("Withdraw");
        withdrawbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawbuttonActionPerformed(evt);
            }
        });

        transferbutton.setBackground(new java.awt.Color(204, 255, 255));
        transferbutton.setText("Transfer");
        transferbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferbuttonActionPerformed(evt);
            }
        });

        interestbutton.setBackground(new java.awt.Color(204, 255, 255));
        interestbutton.setText("Apply interest");
        interestbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interestbuttonActionPerformed(evt);
            }
        });

        viewbutton.setBackground(new java.awt.Color(255, 255, 204));
        viewbutton.setText("View Accounts");
        viewbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbuttonActionPerformed(evt);
            }
        });

        searchbutton.setBackground(new java.awt.Color(255, 255, 204));
        searchbutton.setText("Search Accounts");
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });

        transbutton.setBackground(new java.awt.Color(255, 255, 204));
        transbutton.setText("Transactions History");
        transbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transbuttonActionPerformed(evt);
            }
        });

        logoutbutton.setBackground(new java.awt.Color(255, 51, 51));
        logoutbutton.setText("Log Out");
        logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbuttonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Home");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(newaccbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modifybutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(closebutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(depositbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(withdrawbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(transferbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(interestbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(transbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logoutbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                        .addGap(54, 54, 54)))
                .addGap(332, 332, 332))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(newaccbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modifybutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closebutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(depositbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(withdrawbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(transferbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(interestbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(transbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logoutbutton)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newaccbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newaccbuttonActionPerformed
        // TODO add your handling code here:
        new adding().setVisible(true);
               this.dispose();    
    }//GEN-LAST:event_newaccbuttonActionPerformed

    private void depositbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositbuttonActionPerformed
new Deposit().setVisible(true);
                this.dispose();          
// TODO add your handling code here:
    }//GEN-LAST:event_depositbuttonActionPerformed

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
   new Search().setVisible(true);
               this.dispose(); 
        // TODO add your handling code here:
    }//GEN-LAST:event_searchbuttonActionPerformed

    private void logoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbuttonActionPerformed
 new login().setVisible(true);
               this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_logoutbuttonActionPerformed

    private void modifybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifybuttonActionPerformed
       
        new modify().setVisible(true);
               this.dispose();
    }//GEN-LAST:event_modifybuttonActionPerformed

    private void closebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebuttonActionPerformed
new delete().setVisible(true);
               this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_closebuttonActionPerformed

    private void withdrawbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawbuttonActionPerformed
new withdraw().setVisible(true);
                this.dispose();  
        // TODO add your handling code here:
    }//GEN-LAST:event_withdrawbuttonActionPerformed

    private void transferbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferbuttonActionPerformed
new Transfer().setVisible(true);
            this.dispose(); 
                // TODO add your handling code here:
    }//GEN-LAST:event_transferbuttonActionPerformed

    private void interestbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interestbuttonActionPerformed
Savings a = new Savings();
       int g=  a.applyinterset();
       if(g==0){JOptionPane.showMessageDialog(null, "interest applied sucesfully!");}
      //     int g = applyinterset();
        // TODO add your handling code here:
    }//GEN-LAST:event_interestbuttonActionPerformed

    private void viewbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbuttonActionPerformed

new view().setVisible(true);
                this.dispose();           // TODO add your handling code here:
    }//GEN-LAST:event_viewbuttonActionPerformed

    private void transbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transbuttonActionPerformed
 new transhistory().setVisible(true);
               this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_transbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closebutton;
    private javax.swing.JButton depositbutton;
    private javax.swing.JButton interestbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logoutbutton;
    private javax.swing.JButton modifybutton;
    private javax.swing.JButton newaccbutton;
    private javax.swing.JButton searchbutton;
    private javax.swing.JButton transbutton;
    private javax.swing.JButton transferbutton;
    private javax.swing.JButton viewbutton;
    private javax.swing.JButton withdrawbutton;
    // End of variables declaration//GEN-END:variables
}
